# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a83edd17cec5f1b4c610ad27ca9ce4c57f68c513f4ce853b84961311058a5317c283b2cd455d9fdb919b359f0935260e511e47f235f9f76f4d46067f96779c54

test:
  secret_key_base: 8458ebe826e039bdac9dddb03f76196858c493bcb64e5a7b62404332bd0a55c296526e5e9b5c869c3b8433fd606915587ec1d9928a1823588c7bbbde70969e14

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
